
import os
import sys
import subprocess
import argparse

def main():
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Build brew cask for SwipeAeroSpace')
    parser.add_argument('--build-version', type=str, required=True, help='Build version')
    args = parser.parse_args()
    
    
    # Default values
    cask_name = 'swipeaerospace'
    cask_version = args.build_version
    app_bundle_dir_name = 'SwipeAeroSpace.app'
    zip_uri = f"https://github.com/MediosZ/SwipeAeroSpace/releases/download/{cask_version}/SwipeAeroSpace.zip"

    # Process ZIP file
    zip_file = ''
    if os.path.isfile(zip_uri):
        zip_file = zip_uri
        zip_uri = f"file://{os.path.realpath(zip_file)}"
    elif zip_uri.startswith('http'):
        zip_file = '/tmp/AeroSpace-tmp.zip'
        if os.path.exists(zip_file):
            os.remove(zip_file)
        subprocess.run(['curl', '-L', zip_uri, '-o', zip_file], check=True)
    else:
        sys.stderr.write(f"{zip_uri} doesn't exist\n")
        sys.exit(1)
    
    # Calculate SHA256
    sha = subprocess.check_output(['shasum', '-a', '256', zip_file]).decode('utf-8').split()[0]

    # Generate the Ruby file
    cask_template = f"""cask "{cask_name}" do # THE FILE IS GENERATED BY build-brew-cask.py
  version "{cask_version}"
  sha256 "{sha}"

  url "https://github.com/MediosZ/SwipeAeroSpace/releases/download/#{{version}}/SwipeAeroSpace.zip"
  name "SwipeAeroSpace"
  desc "SwipeAeroSpace is a tool to switch AeroSpace worksapces by swiping."
  homepage "https://github.com/MediosZ/SwipeAeroSpace"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{{appdir}}/{app_bundle_dir_name}"
  end

  app "{app_bundle_dir_name}"
end
"""
    
    with open(f"{cask_name}.rb", "w") as f:
        f.write(cask_template)


if __name__ == "__main__":
    main()